### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by Carson-Davis** [CSBSJU-CS330-F22/WeatherApp#22]
As a developer I want to create project init files and file structures so that it is organized and ready to be worked on

Acceptance Criteria:
- simple and descriptive names

Tasks:
- Create init files
- Organize file structure
- Host files on GitHub

**Comment by maxwellvogel** [comment]
9be7960 / 9be7960b6213ae400213ff5d7c90e6c7b5aa21b9 includes initial commit of Kotlin project structure.  Other group members can now create a fork of this repository and clone to their own environments.
