### ISSUE TITLE
API Wrapper

### ISSUE THREAD

**Issue by Carson-Davis** [CSBSJU-CS330-F22/WeatherApp#24]
As a developer I want a class that calls wrapper methods on a weather API so that I have access to information

Acceptance Criteria:
- Wrapper methods to grab information
- formatted for easy API swap-outs

Tasks:
- Testing
- Read in JSON data
- Return appropriate data

**Comment by maxwellvogel** [comment]
A class named WeatherAPI was created that contains a val of httpClient, which acts as the primary interface for making API calls to api.weather.gov.  The interface handles the deserializing of JSON data to our custom data classes that match the api data.  This class also contents (and will contain more) methods dedicated to using the httpClient to make specific requests and return the data as our data classes.
